<Project Sdk="MSBuild.Sdk.Extras/2.0.54">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;MonoAndroid81;Xamarin.iOS10;uap10.0.18362;net462</TargetFrameworks>
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
    <Version>2.4.3.5</Version>
    <Authors>gentledpp,bruzkovsky</Authors>
    <Company>Opti-Q GmbH</Company>
    <PackageReleaseNotes>
		# 2.4.3.5
		- changed "Href" property of SvgImage from Uri to string, as System.Uri throws in case a url is too long

		# 2.4.3.4
		- antialiasing on by default

		# 2.4.3.3
		netstandard multiplatform
	</PackageReleaseNotes>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="$(Configuration) == 'Release'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSource>True</IncludeSource>
    <IncludeSymbols>True</IncludeSymbols>
  </PropertyGroup>

  <PropertyGroup Condition="$(TargetFramework.StartsWith('net4')) ">
    <DefineConstants>Net4</DefineConstants>
  </PropertyGroup>


  <ItemGroup>
    <Compile Remove="Platforms\**\*.cs" />
    <None Include="Platforms\**\*.cs" />
  </ItemGroup>

  <ItemGroup Condition=" $(TargetFramework.StartsWith('uap')) ">
    <Compile Include="Platforms\UniversalWindows\**\*.cs" />
  </ItemGroup>

  <ItemGroup Condition=" $(TargetFramework.StartsWith('MonoAndroid')) ">
    <Compile Include="Platforms\Android\**\*.cs" />
    <PackageReference Include="System.Xml.ReaderWriter" Version="4.3.0" />

  </ItemGroup>

  <ItemGroup Condition=" $(TargetFramework.StartsWith('Xamarin.iOS')) ">
    <Compile Include="Platforms\iOS\**\*.cs" />
  </ItemGroup>

  <ItemGroup Condition=" $(TargetFramework.StartsWith('net4')) ">
    <Compile Include="Platforms\Win\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="1.68.1" />
  </ItemGroup>


</Project>
