<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <AssemblyName>SvgW3CTestSuite.Assets</AssemblyName>
        <RootNamespace>SvgW3CTestSuite.Assets</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <!-- Images -->
        <EmbeddedResource Include="..\Tests\W3CTestSuite\images\**\*" Link="images\%(RecursiveDir)%(Filename)%(Extension)" />

        <!-- PNG files -->
        <EmbeddedResource Include="..\Tests\W3CTestSuite\png\**\*" Link="png\%(RecursiveDir)%(Filename)%(Extension)" />

        <!-- SVG files -->
        <EmbeddedResource Include="..\Tests\W3CTestSuite\svg\**\*" Link="svg\%(RecursiveDir)%(Filename)%(Extension)" />

        <!-- Resources -->
        <EmbeddedResource Include="..\Tests\W3CTestSuite\resources\**\*" Link="resources\%(RecursiveDir)%(Filename)%(Extension)" />

        <!-- Test files -->
        <EmbeddedResource Include="..\Tests\W3CTestSuite\PassingTests.txt" Link="PassingTests.txt" />
    </ItemGroup>

</Project>