<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<Version>3.0.8-alpha-avalonia</Version>
		<PackageReleaseNotes>
			#3.0.0-alpha-avalonia
			migrate to avalonia
		</PackageReleaseNotes>
	</PropertyGroup>

	<PropertyGroup Condition="$(Configuration) == 'Release'">
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<IncludeSource>True</IncludeSource>
		<IncludeSymbols>True</IncludeSymbols>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.3.9" />
		<PackageReference Include="Avalonia.Skia" Version="11.3.9" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Svg.Editor.Core\Svg.Editor.Core.csproj" />
	</ItemGroup>

</Project>