<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0-windows</TargetFrameworks>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">13.0</SupportedOSPlatformVersion>

	</PropertyGroup>

	<PropertyGroup Condition="$(Configuration) == 'Release'">
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<IncludeSource>True</IncludeSource>
		<IncludeSymbols>True</IncludeSymbols>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Platforms\**\*.cs" />
		<None Include="Platforms\**\*.cs" />
	</ItemGroup>

	<ItemGroup Condition=" $(TargetFramework.Contains('-windows')) ">
		<Compile Include="Platforms\Windows\**\*.cs" />
	</ItemGroup>

	<!--
	<PropertyGroup Condition=" $(TargetFramework.StartsWith('net8.0-android')) ">
		<AndroidUseIntermediateDesignerFile>False</AndroidUseIntermediateDesignerFile>
		-->
	<!--<XamarinGoogleGuavaListenableFutureOptOut>true</XamarinGoogleGuavaListenableFutureOptOut>--><!--
	</PropertyGroup>
	<ItemGroup Condition=" $(TargetFramework.StartsWith('net8.0-android')) ">
		<Compile Include="Platforms\Android\**\*.cs" />
		--><!--<PackageReference Include="Xamarin.AndroidX.Core.SplashScreen" Version="1.0.1.1" />--><!--
	</ItemGroup>

	<ItemGroup Condition=" $(TargetFramework.StartsWith('net8.0-ios')) ">
		<Compile Include="Platforms\iOS\**\*.cs" />
</ItemGroup>-->

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.2.1" />
		<PackageReference Include="Avalonia.ReactiveUI" Version="11.2.1" />
		<PackageReference Include="MessageBox.Avalonia" Version="3.2.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Svg.Editor.Core\Svg.Editor.Core.csproj" />
	</ItemGroup>
</Project>