<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<PropertyGroup Condition="$(Configuration) == 'Release'">
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<IncludeSource>True</IncludeSource>
		<IncludeSymbols>True</IncludeSymbols>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.2.1" />
		<PackageReference Include="Avalonia.Skia" Version="11.2.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Svg.Editor.Core\Svg.Editor.Core.csproj" />
	</ItemGroup>

</Project>