<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Svg.Editor.Sample.Forms</RootNamespace>
    <AssemblyName>Svg.Editor.Sample.Forms</AssemblyName>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Svg.Editor.Core\Svg.Editor.Core.csproj" />
    <ProjectReference Include="..\..\Svg.Editor.Forms\Svg.Editor.Forms.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\svg\ic_save.svg" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Acr.UserDialogs" Version="6.3.9" />
    <PackageReference Include="SkiaSharp.Views.Forms" Version="1.68.1" />
    <PackageReference Include="Svg" Version="2.4.4.11" />
    <PackageReference Include="System.Reactive" Version="4.0.0" />
    <PackageReference Include="Xam.Plugin.Media" Version="4.0.1.5" />
    <PackageReference Include="Xamarin.Forms" Version="4.1.0.778454" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
</Project>