<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>3.0.0.0-maui</Version>
		<PckageReleaseNotes>
			#3.0.0.0-maui
			migrated to maui
		</PckageReleaseNotes>
		<TargetFrameworks>net7.0;net7.0-android;net7.0-ios</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041.0</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net6.0-tizen</TargetFrameworks> -->
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">14.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
	</PropertyGroup>



	<PropertyGroup Condition="$(Configuration) == 'Release'">
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<IncludeSource>True</IncludeSource>
		<IncludeSymbols>True</IncludeSymbols>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Platforms\**\*.cs" />
		<None Include="Platforms\**\*.cs" />
	</ItemGroup>

	<ItemGroup Condition=" $(TargetFramework.Contains('-windows')) ">
		<Compile Include="Platforms\Windows\**\*.cs" />
	</ItemGroup>

	<PropertyGroup Condition=" $(TargetFramework.StartsWith('net7.0-android')) ">
		<AndroidUseIntermediateDesignerFile>False</AndroidUseIntermediateDesignerFile>
	</PropertyGroup>
	<ItemGroup Condition=" $(TargetFramework.StartsWith('net7.0-android')) ">
		<Compile Include="Platforms\Android\**\*.cs" />

		<PackageReference Include="Plugin.Maui.CurrentActivity" Version="1.0.0.61" />
	</ItemGroup>

	<ItemGroup Condition=" $(TargetFramework.StartsWith('net7.0-ios')) ">
		<Compile Include="Platforms\iOS\**\*.cs" />

		<!-- Fix bug with System.Reflection.Emit (see: https://github.com/xamarin/Xamarin.Forms/issues/1380) -->
		<PackageReference Include="System.Reflection.Emit" Version="4.3.0">
			<ExcludeAssets>all</ExcludeAssets>
		</PackageReference>
	</ItemGroup>


	<ItemGroup>
		<PackageReference Include="Svg" Version="3.0.0.1-maui1" />
		<PackageReference Include="System.Reactive" Version="4.0.0" />
		<PackageReference Include="SkiaSharp.Views.Maui.Controls.Compatibility" Version="2.88.3" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Svg.Editor.Core\Svg.Editor.Core.csproj" />
	  <ProjectReference Include="..\Svg.Editor.View\Svg.Editor.View.csproj" />
	</ItemGroup>

</Project>
