<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net48;net10.0</TargetFrameworks>
        <OutputType>Library</OutputType>
        <RootNamespace>Svg.Tests.Win</RootNamespace>
        <AssemblyName>Svg.Tests.Win</AssemblyName>
        <LangVersion>latest</LangVersion>
        <UseWPF>false</UseWPF>
        <UseWindowsForms>false</UseWindowsForms>
        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
        <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Debug'">
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <Optimize>false</Optimize>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <DebugType>pdbonly</DebugType>
        <Optimize>true</Optimize>
        <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.DotMemoryUnit" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Moq" />
        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit3TestAdapter" />
        <PackageReference Include="Shouldly" />
        <PackageReference Include="SkiaSharp" />
        <PackageReference Include="System.Buffers" />
        <PackageReference Include="System.Memory" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Svg\Svg.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\Svg.Editor.Tests.Win\FileLoader.cs" Link="FileLoader.cs" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Assets\**\*" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Properties\" />
    </ItemGroup>

    <Import Project="..\Svg.Tests\Svg.Tests.projitems" Label="Shared" />

</Project>