<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Authors>gentledpp,bruzkovsky</Authors>
    <Company>Opti-Q GmbH</Company>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

    <ItemGroup>
      <Compile Include="..\Svg.Editor.Tests.Win\FileLoader.cs" Link="FileLoader.cs" />
    </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="SkiaSharp" Version="1.68.1" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Svg\Svg.csproj" />
  </ItemGroup>


  <Import Project="..\Svg.Tests\Svg.Tests.projitems" Label="Shared" />
</Project>


