<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Authors>gentledpp,bruzkovsky</Authors>
    <Company>Opti-Q GmbH</Company>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="SkiaSharp" Version="1.68.1" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\SvgW3CTestSuite.Assets\SvgW3CTestSuite.Assets.csproj" />
    <ProjectReference Include="..\Svg\Svg.csproj" />
  </ItemGroup>
</Project>


