<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <RootNamespace>SvgW3CTestSuite.Win</RootNamespace>
        <AssemblyName>SvgW3CTestSuite.Win</AssemblyName>
        <LangVersion>latest</LangVersion>
        <OutputType>Library</OutputType>
        <Platforms>AnyCPU;x86</Platforms>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Debug'">
        <DefineConstants>TRACE;DEBUG;WIN</DefineConstants>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <Optimize>false</Optimize>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <DefineConstants>TRACE;WIN</DefineConstants>
        <DebugType>pdbonly</DebugType>
        <Optimize>true</Optimize>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NUnit" Version="3.12.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SvgW3CTestSuite.Assets\SvgW3CTestSuite.Assets.csproj" />
        <ProjectReference Include="..\Svg\Svg.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Properties\" />
    </ItemGroup>

    <Import Project="..\SvgW3CTestSuite.Shared\SvgW3CTestSuite.Shared.projitems" Label="Shared" />

</Project>