<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\svg\ic_save.svg" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\svg\ic_save.svg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.2.1" />
    <PackageReference Include="MessageBox.Avalonia" Version="3.2.0" />
	  <PackageReference Include="Avalonia" Version="11.2.1" />
	  <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.1" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.2.1">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Svg.Editor.Avalonia.Forms\Svg.Editor.Avalon.Forms.csproj" />
    <ProjectReference Include="..\Svg.Editor.Avalonia.Views\Svg.Editor.Avalon.Views.csproj" />
    <ProjectReference Include="..\Svg.Editor.Core\Svg.Editor.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="MainWindow.axaml.cs">
      <DependentUpon>MainWindow.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
