<Project Sdk="MSBuild.Sdk.Extras/2.0.46">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;MonoAndroid81;Xamarin.iOS10;uap10.0.17763</TargetFrameworks>
    <Version>2.4.3.7</Version>
    <PackageReleaseNotes>
        # 2.4.3.7
        - Svg 2.4.5.7
		# 2.4.3.6
		- bumped version for Svg 2.4.3.5
		# 2.4.3.5
		- fixed UWP gesture recognizer
		# 2.4.3.4
		- fixed for plan rendering
		- polygon tool improvements (selection rendered on adorner layer)
		# 2.4.3.3
		- polygon tool
		- hit testing basic shapes without fill tests line intersection
	</PackageReleaseNotes>
  </PropertyGroup>

  <PropertyGroup Condition="$(Configuration) == 'Release'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSource>True</IncludeSource>
    <IncludeSymbols>True</IncludeSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Platforms\**\*.cs" />
    <None Include="Platforms\**\*.cs" />
  </ItemGroup>

  <ItemGroup Condition=" $(TargetFramework.StartsWith('uap')) ">
    <Compile Include="Platforms\UniversalWindows\**\*.cs" />
  </ItemGroup>

  <PropertyGroup Condition=" $(TargetFramework.StartsWith('MonoAndroid')) ">
    <AndroidUseIntermediateDesignerFile>False</AndroidUseIntermediateDesignerFile>
  </PropertyGroup>
  <ItemGroup Condition=" $(TargetFramework.StartsWith('MonoAndroid')) ">
    <Compile Include="Platforms\Android\**\*.cs" />

    <PackageReference Include="Plugin.CurrentActivity" Version="2.1.0.4" />
  </ItemGroup>

  <ItemGroup Condition=" $(TargetFramework.StartsWith('Xamarin.iOS')) ">
    <Compile Include="Platforms\iOS\**\*.cs" />

    <!-- Fix bug with System.Reflection.Emit (see: https://github.com/xamarin/Xamarin.Forms/issues/1380) -->
    <PackageReference Include="System.Reflection.Emit" Version="4.3.0">
      <ExcludeAssets>all</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Svg.Editor.Core\Svg.Editor.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp.Views" Version="1.68.1" />
  </ItemGroup>

</Project>