namespace Svg.Interfaces
{
    public interface Colors
    {
        Color Transparent { get; } 
        Color AliceBlue { get; } 
        Color LightSalmon { get; } 
        Color AntiqueWhite { get; } 
        Color LightSeaGreen { get; } 
        Color Aqua { get; } 
        Color LightSkyBlue { get; } 
        Color Aquamarine { get; } 
        Color LightSlateGray { get; } 
        Color Azure { get; } 
        Color LightSteelBlue { get; } 
        Color Beige { get; } 
        Color LightYellow { get; } 
        Color Bisque { get; } 
        Color Lime { get; } 
        Color Black { get; } 
        Color LimeGreen { get; } 
        Color BlanchedAlmond { get; } 
        Color Linen { get; } 
        Color Blue { get; } 
        Color Magenta { get; } 
        Color BlueViolet { get; } 
        Color Maroon { get; } 
        Color Brown { get; } 
        Color MediumAquamarine { get; } 
        Color BurlyWood { get; } 
        Color MediumBlue { get; } 
        Color CadetBlue { get; } 
        Color MediumOrchid { get; } 
        Color Chartreuse { get; } 
        Color MediumPurple { get; } 
        Color Chocolate { get; } 
        Color MediumSeaGreen { get; } 
        Color Coral { get; } 
        Color MediumSlateBlue { get; } 
        Color CornflowerBlue { get; } 
        Color MediumSpringGreen { get; } 
        Color Cornsilk { get; } 
        Color MediumTurquoise { get; } 
        Color Crimson { get; } 
        Color MediumVioletRed { get; } 
        Color Cyan { get; } 
        Color MidnightBlue { get; } 
        Color DarkBlue { get; } 
        Color MintCream { get; } 
        Color DarkCyan { get; } 
        Color MistyRose { get; } 
        Color DarkGoldenrod { get; } 
        Color Moccasin { get; } 
        Color DarkGray { get; } 
        Color NavajoWhite { get; } 
        Color DarkGreen { get; } 
        Color Navy { get; } 
        Color DarkKhaki { get; } 
        Color OldLace { get; } 
        Color DarkMagena { get; } 
        Color Olive { get; } 
        Color DarkOliveGreen { get; } 
        Color OliveDrab { get; } 
        Color DarkOrange { get; } 
        Color Orange { get; } 
        Color DarkOrchid { get; } 
        Color OrangeRed { get; } 
        Color DarkRed { get; } 
        Color Orchid { get; } 
        Color DarkSalmon { get; } 
        Color PaleGoldenrod { get; } 
        Color DarkSeaGreen { get; } 
        Color PaleGreen { get; } 
        Color DarkSlateBlue { get; } 
        Color PaleTurquoise { get; } 
        Color DarkSlateGray { get; } 
        Color PaleVioletRed { get; } 
        Color DarkTurquoise { get; } 
        Color PapayaWhip { get; } 
        Color DarkViolet { get; } 
        Color PeachPuff { get; } 
        Color DeepPink { get; } 
        Color Peru { get; } 
        Color DeepSkyBlue { get; } 
        Color Pink { get; } 
        Color DimGray { get; } 
        Color Plum { get; } 
        Color DodgerBlue { get; } 
        Color PowderBlue { get; } 
        Color Firebrick { get; } 
        Color Purple { get; } 
        Color FloralWhite { get; } 
        Color Red { get; } 
        Color ForestGreen { get; } 
        Color RosyBrown { get; } 
        Color Fuschia { get; } 
        Color RoyalBlue { get; } 
        Color Gainsboro { get; } 
        Color SaddleBrown { get; } 
        Color GhostWhite { get; } 
        Color Salmon { get; } 
        Color Gold { get; } 
        Color SandyBrown { get; } 
        Color Goldenrod { get; } 
        Color SeaGreen { get; } 
        Color Gray { get; } 
        Color Seashell { get; } 
        Color Green { get; } 
        Color Sienna { get; } 
        Color GreenYellow { get; } 
        Color Silver { get; } 
        Color Honeydew { get; } 
        Color SkyBlue { get; } 
        Color HotPink { get; } 
        Color SlateBlue { get; } 
        Color IndianRed { get; } 
        Color SlateGray { get; } 
        Color Indigo { get; } 
        Color Snow { get; } 
        Color Ivory { get; } 
        Color SpringGreen { get; } 
        Color Khaki { get; } 
        Color SteelBlue { get; } 
        Color Lavender { get; } 
        Color Tan { get; } 
        Color LavenderBlush { get; } 
        Color Teal { get; } 
        Color LawnGreen { get; } 
        Color Thistle { get; } 
        Color LemonChiffon { get; } 
        Color Tomato { get; } 
        Color LightBlue { get; } 
        Color Turquoise { get; } 
        Color LightCoral { get; } 
        Color Violet { get; } 
        Color LightCyan { get; } 
        Color Wheat { get; } 
        Color LightGoldenrodYellow { get; } 
        Color White { get; } 
        Color LightGreen { get; } 
        Color WhiteSmoke { get; } 
        Color LightGray { get; } 
        Color Yellow { get; } 
        Color LightPink { get; } 
        Color YellowGreen { get; }

        Color FromName(string name);
    }
}
