<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Svg.Editor</RootNamespace>
    <AssemblyName>Svg.Editor</AssemblyName>
    <DefaultLanguage>en-US</DefaultLanguage>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Version>2.4.1</Version>
    <PackageReleaseNotes>
    </PackageReleaseNotes>
  </PropertyGroup>

  <PropertyGroup Condition="$(Configuration) == 'Release'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSource>True</IncludeSource>
    <IncludeSymbols>True</IncludeSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Assets\" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\svg\ic_arrow_downward.svg" />
    <EmbeddedResource Include="Resources\svg\ic_arrow_upward.svg" />
    <EmbeddedResource Include="Resources\svg\ic_aspect_ratio.svg" />
    <EmbeddedResource Include="Resources\svg\ic_border_style.svg" />
    <EmbeddedResource Include="Resources\svg\ic_brush.svg" />
    <EmbeddedResource Include="Resources\svg\ic_code.svg" />
    <EmbeddedResource Include="Resources\svg\ic_color_lens.svg" />
    <EmbeddedResource Include="Resources\svg\ic_delete.svg" />
    <EmbeddedResource Include="Resources\svg\ic_flip_to_back.svg" />
    <EmbeddedResource Include="Resources\svg\ic_flip_to_front.svg" />
    <EmbeddedResource Include="Resources\svg\ic_format_color_fill.svg" />
    <EmbeddedResource Include="Resources\svg\ic_grid_off.svg" />
    <EmbeddedResource Include="Resources\svg\ic_grid_on.svg" />
    <EmbeddedResource Include="Resources\svg\ic_insert_photo.svg" />
    <EmbeddedResource Include="Resources\svg\ic_line_endings.svg" />
    <EmbeddedResource Include="Resources\svg\ic_line_style.svg" />
    <EmbeddedResource Include="Resources\svg\ic_mode_edit.svg" />
    <EmbeddedResource Include="Resources\svg\ic_pan_tool.svg" />
    <EmbeddedResource Include="Resources\svg\ic_pin_resize.svg" />
    <EmbeddedResource Include="Resources\svg\ic_pin_tool.svg" />
    <EmbeddedResource Include="Resources\svg\ic_panorama_fish_eye.svg" />
    <EmbeddedResource Include="Resources\svg\ic_redo.svg" />
    <EmbeddedResource Include="Resources\svg\ic_rotate_left.svg" />
    <EmbeddedResource Include="Resources\svg\ic_rotate_right.svg" />
    <EmbeddedResource Include="Resources\svg\ic_save.svg" />
    <EmbeddedResource Include="Resources\svg\ic_select.svg" />
    <EmbeddedResource Include="Resources\svg\ic_swap_vert.svg" />
    <EmbeddedResource Include="Resources\svg\ic_text_fields.svg" />
    <EmbeddedResource Include="Resources\svg\ic_undo.svg" />
    <EmbeddedResource Include="Resources\svg\ic_zoom.svg" />
    <EmbeddedResource Include="Resources\svg\ic_zoom_100.svg" />
    <EmbeddedResource Include="Resources\svg\ic_zoom_200.svg" />
    <EmbeddedResource Include="Resources\svg\ic_zoom_in.svg" />
    <EmbeddedResource Include="Resources\svg\ic_zoom_out.svg" />
    <EmbeddedResource Include="Resources\svg\ic_crop_square.svg" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
    <PackageReference Include="SkiaSharp" Version="1.68.1" />
    <PackageReference Include="Svg" Version="2.4.0.2" />
    <PackageReference Include="System.Reactive" Version="4.0.0" />
  </ItemGroup>
</Project>