<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-ios17.5</TargetFramework>
    <SupportedOSPlatformVersion>12.4</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.iOS" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Svg.Editor.Avalonia.Forms\Svg.Editor.Avalon.Forms.csproj" />
    <ProjectReference Include="..\..\Svg.Editor.Avalonia.Views\Svg.Editor.Avalon.Views.csproj" />
    <ProjectReference Include="..\Svg.Editor.CrossSample.Avalon\Svg.Editor.CrossSample.Avalon.csproj" />
  </ItemGroup>
</Project>
